# Iterative/semi-amortized VAE with CNN backbone
type: ivae_iterative          # Consumed by build_model_from_cfg
arch: conv                    # Force CNN backbone (ConvEncoder/ConvDecoder)

# Latent + optimization hyperparameters
z_dim: 32
beta: 1.0
lr: 1e-4                      # Learning rate for encoder/decoder params
lr_inf: 1e-2                  # Learning rate for inner-loop SVI (mu, logvar)
svi_steps: 20                 # Number of SVI refinement steps per batch
weight_decay: 0.0

# CNN channel schedules (MNIST-like 1x28x28 defaults)
conv_hidden: [32, 64]         # Downsampling encoder channels
deconv_hidden: [64, 32]       # Upsampling decoder channels

# Optional checkpoint to initialize encoder/decoder weights
# If provided but arch omitted, architecture can be inferred from checkpoint
init_weights: null

