dataset:
  name: mnist
  data_dir: ./data
  batch_size: 256
  num_workers: 4
  pin_memory: True

model:
  type: ivae_iterative                # choices: vae_mlp, vae_conv, ivae_iterative
  z_dim: 15
  lr: 1e-3
  beta: 2.0
  weight_decay: 0.0

train:
  epochs: 100
  save_dir: ./runs/test1
  use_amp: True
  early_stopping: True
  patience: 10
  save_top_k: 3
  grad_clip: 1.0
