dataset:
  name: mnist
  batch_size: 1024
  num_workers: 0

model:
  type: ivae_iterative                # choices: vae_mlp, vae_conv, ivae_iterative
  arch: conv                    # Force CNN backbone (ConvEncoder/ConvDecoder)
  beta: 2.0
  init_weightss: null               # Optional path to a pretrained VAE checkpoint to initialise from

train:
  epochs: 220
  save_dir: ./runs/ivae_conv
  use_amp: True
  early_stopping: True
  patience: 10
  save_top_k: 2
  grad_clip: 0.0 #set to 0.0 to disable for ivae models