dataset:
  name: mnist
  batch_size: 1024
  num_workers: 0

model:
  type: ivae_iterative                # choices: vae_mlp, vae_conv, ivae_iterative
  beta: 2.0

train:
  epochs: 220
  save_dir: ./runs/ivae_iterative_mlp
  use_amp: True
  early_stopping: True
  grad_clip: 0.0
  patience: 10
  save_top_k: 2
  grad_clip: 1.0
